### ISSUE TITLE
Leviton Switches Not Displayed

### ISSUE THREAD

**Issue by anthonylavado** [davidgruhin/WinkPost#3]
Just set this up locally on my Mac this evening, and I can see my Hub, my Nest Protect, and my Nest Thermostat, but not my two Leviton Z-Wave switches.

Haven't had a chance to investigate why this is yet, but I do know that the other integration works (I can adjust the temperature of my Nest Thermostat successfully).

![screen shot 2015-02-19 at 10 14 19 pm](https://cloud.githubusercontent.com/assets/596194/6280953/adc911ea-b884-11e4-87fc-d8228cab522d.png)

**Comment by anthonylavado** [comment]
Just looked at this again quickly- they get displayed for a brief moment when it fetches devices, and acknowledges that there are five present. They quickly disappear, making me believe they are being hidden by jQuery as unsupported in this case.

**Comment by davidgruhin** [comment]
I hid some stuff with Jquery. I will update tomorrow and push the changes.

Sent from my iPhone

On Feb 19, 2015, at 10:19 PM, anthonylavado <notifications@github.com>
wrote:

Just looked at this again quickly- they get displayed for a brief moment
when it fetches devices, and acknowledges that there are five present. They
quickly disappear, making me believe they are being hidden by jQuery as
unsupported in this case.

—
Reply to this email directly or view it on GitHub
<https://github.com/davidgruhin/WinkPost/issues/3#issuecomment-75183681>.

**Comment by davidgruhin** [comment]
I just pushed a code update to remove the Jquery I put in for testing purposes and shortened the refresh time for device polling.
