### ISSUE TITLE
Nest Thermostat displays wrong scale

### ISSUE THREAD

**Issue by anthonylavado** [davidgruhin/WinkPost#4]
My Nest Thermostat is being returned in Fahrenheit as opposed to Celsius.
It is set correctly in both the Nest and Wink apps, and shows up correctly in both.

Perhaps the info still gets delivered in Fº and then gets converted by the app?

This can be seen in https://github.com/davidgruhin/WinkPost/issues/3.

**Comment by davidgruhin** [comment]
This is caused by the temperature calculation in js/wink.js

lines 139 and 140

var nTemp = wink.desired_state.max_set_point;
nTemp = (nTemp * 1.8) + 32;

You can adjust line 140 to calculate C* instead of F* by simply removing the math

nTemp = nTemp;

ºF =ºC * 1.8000 + 32.00

**Comment by davidgruhin** [comment]
I modified the code, you can just comment out the line 

nTemp = (nTemp * 1.8) + 32;

Wink's api reports in celsius to begin with.

**Comment by anthonylavado** [comment]
Noted. Thank you.

I know the API shows the units it reports in, so is it always Celsius? If so, then I imagine the app calculates the conversion based on user account preference? 

If not, I can look at adding in the code to pull the unit field out of the thermostat json, and display appropriately.
